n_steps: 20
batch_size: 64
learning_rate: 0.000125
gamma: 0.99
ent_coef: 7.5e-08
clip_range: 0.2
n_epochs: 5
gae_lambda: 0.95
max_grad_norm: 0.9
vf_coef: 0.95
device: "cuda:0"
total_timesteps: 1000000
